# Kernel and System-Level Chaos
# Kernel panic, syscall filtering, and resource exhaustion

---
# File Descriptor Exhaustion - Exhaust file descriptors
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: file-descriptor-exhaustion
  namespace: chaos-demo
spec:
  mode: one
  selector:
    namespaces:
      - chaos-demo
    labelSelectors:
      app: backend
  stressors:
    filesystem:
      workers: 2
      size: "500Mi"
  duration: "2m"
---
# Process Exhaustion - Spawn many child processes
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: process-exhaustion
  namespace: chaos-demo
spec:
  mode: one
  selector:
    namespaces:
      - chaos-demo
    labelSelectors:
      app: backend
  stressors:
    cpu:
      workers: 4
      load: 100
  duration: "1m"
